title: Personal website of Jared Wiltshire
description: >-
  Personal website of Jared Wiltshire, software developer at Radix IoT.
url: "https://jazdw.net"
github_username:  jazdw
theme: minima
permalink: /:categories/:year/:month/:day/:slug
plugins:
  - jekyll-sitemap
